<?php

/**@var \Papeo\Formation2\Block\Cadeau\Liste $block */

$clients = $block->getMesClients();
/**
 * @var \Magento\Customer\Model\Customer $client
 */

/**
 * @var \Papeo\Formation2\Model\Cadeau $cadeau
 */

$cadeau = $block->getMonCadeau();
// 1. GET request : Get booking data
$id = $this->getRequest()->getParam("id", false);
$nom_client = $cadeau->getData("nom_client");
$nom_cadeau = $cadeau->getData("nom_cadeau");
?>

<form method="post" action=<?php echo $block->getUrl("*/*/UpdatePost"); ?>">
    <input type="text" name="nom_cadeau" id="nom_cadeau" value="<?php echo $nom_cadeau; ?>">
    <select name="nom_client" id="nom_client">
        <?php
        echo "<option selected>".$nom_client."</option>";
        foreach ($clients as $client) {
            echo "<option value='" . $client->getName() . "'>" . $client->getName()."</option>";
        }
        ?>
    </select>
    <input type="hidden" name="id" id="id" value="<?php echo $cadeau->getId(); ?>">
    <br>
    <p><input type="submit" value="Mettre à jour"/></p>
</form>
<?php







