<?php

/**@var \Papeo\Formation2\Block\Ventes\Liste $block */

$clients = $block->getMesClients();
/**
 * @var \Magento\Customer\Model\Customer $client
 */


$listeVentes = $block->getMesCommandes();

//
echo "<br> Il y a " . count($listeVentes);

echo "<br>Dont voici les noms : <br>";

foreach ($listeVentes as $listeVente) {

    echo "<li>";

    echo $listeVente->getCustomerLastname()." ".$listeVente->getCustomerFirstname()." ". $listeVente->getBaseGrandTotal()."k";



    echo "</li>";
}


?>


