<?php

/**@var \Papeo\ApiRealisaprint\Block\Adminhtml\Fournisseur\Liste $block
 */

/**@var \Papeo\ApiRealisaprint\Block\Adminhtml\Item\Liste $block
 */


$fournisseurs = $block->getFournisseurs();






/**
 * @var \Papeo\ApiRealisaprint\Model\Fournisseur $fournisseur
 */

/**
 * @var \Papeo\ApiRealisaprint\Model\Fournisseur $defautFournisseur
 */

$item = $block->getItem();
$block->escapeHtml(__('Ordered'));
$idCurrentItem = (float) $item->getId();
   // echo "idItem est ". $idCurrentItem;
$idCurrent = $block->getRequest()->getParam("order_id");
$defautFournisseurs = $block->getdefautFournisseur($idCurrentItem);
$defautCdeFournisseur = $block->getdefautCdeFournisseur($idCurrentItem);
$nbItem = $block->getItemCommande($idCurrent);


?>

<form method="get" action="<?php echo $this->getUrl('apirealisaprint/commande/SafeOrder');?>">


    <input type="text" name="NumCdeFournisseur" id="NumCdeFournisseur" value="<?php if($defautCdeFournisseur) echo $defautCdeFournisseur; ?>">
    <input id="idCurrentOrder" name="idCurrentOrder" type="hidden" value="<?php echo $idCurrent; ?>">
    <select name="id_fournisseur" id="id_fournisseur" value="<?php echo $defautFournisseurs; ?>">
        <?php


        echo "<option value=>--Choisissez un fournisseur--</option>";
        foreach ($fournisseurs as $fournisseur) {

?>
            <?php //echo "//" . $fournisseur->getData("revendeur_id") ?>
            <br>
            <br>

<option <?php

if($defautFournisseurs == $fournisseur->getData("revendeur_id")){echo 'selected="selected"';} ?> value="<?php echo $fournisseur->getData("revendeur_id") ; ?>"><?php echo $fournisseur->getData("code_fournisseur"); ?></option>


<?php


        }
?>
</select>
    <?php

//    echo "<br>la commande courante est ". $idCurrent. "<br>";
//    echo "def fourn courante est ". $defautFournisseurs. "<br>";
//    echo "def Cde fourn courante est ". $defautCdeFournisseur. "<br>";


//    Echo "Il y a ". $nbItem. " article(s) dans cette commande."."<br>";?>

 <input type="hidden" id="custId" name="idItem" value="<?= (float) $item->getId();?>">

        <br>
    <button id="envoyer-<?php echo $nbItem;?>">Envoyer</button></p>
</form>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).on('click','#envoyer-<?php echo $nbItem;?>', function() {
            var id_fournisseur = '<?php echo $fournisseur->getData("revendeur_id") ; ?>';
            var NumCdeFournisseur = '<?php echo $defautFournisseurs; ?>';

                var param = {
                    ajax: 1,
                    fp:FP,
                    productId:productId,
                    itemId: '<?php echo $nbItem;?>'}

                $.ajax({
                    showLoader: true,
                    url: '<?php echo $this->getUrl('apirealisaprint/commande/SafeOrder');?>',
                    data: param,
                    type: "GET",
                    dataType: 'json'
                }).done(function (data) {
                    document.location.reload();
                });
            }

        });
</script>


